### ISSUE TITLE
Creating deployments with k8s-kubectl image. Pods are crash looping

### ISSUE THREAD

**Issue by devslam** [lachie83/k8s-kubectl#116]
Apologies if this isn't the right place to post. 

This is my first time playing with kubernetes and docker

I'm trying to create a deployment with the k8s-kubectl image. I've created a service account and cluster role binding; I've declared the service account in the spec of my deployment.

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-101-role
```

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-101-role
subjects:
- kind: ServiceAccount
  name: k8s-101-role
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-101
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-101
  template:
    metadata:
      labels:
        app: k8s-101
    spec:
      serviceAccountName: k8s-101-role
      containers:
      - name: k8s-101
        imagePullPolicy: Always
        image: lachlanevenson/k8s-kubectl:latest
        ports:
        - name: app
          containerPort: 3000
```

Once I create the deployment, it looks the pod is crash looping

```
ubuntu@microk8s-vm:~$ microk8s.kubectl get  deployments
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
k8s-101   0/1     1            0           65m
```

```
ubuntu@microk8s-vm:~$ microk8s.kubectl get pods
NAME                       READY   STATUS             RESTARTS   AGE
k8s-101-768dfd845b-lrwxx   0/1     CrashLoopBackOff   16         61m
```

```
ubuntu@microk8s-vm:~$ microk8s.kubectl describe pod k8s-101-768dfd845b-lrwxx
Name:         k8s-101-768dfd845b-lrwxx
Namespace:    default
Priority:     0
Node:         microk8s-vm/192.168.64.2
Start Time:   Fri, 10 Jan 2020 00:33:41 -0500
Labels:       app=k8s-101
              pod-template-hash=768dfd845b
Annotations:  <none>
Status:       Running
IP:           10.1.76.5
IPs:
  IP:           10.1.76.5
Controlled By:  ReplicaSet/k8s-101-768dfd845b
Containers:
  k8s-101:
    Container ID:   containerd://6fdb8914e5a049bef032c1913618a56ba8c54dc3b145fc03dbb9a6eed4905a6a
    Image:          lachlanevenson/k8s-kubectl:latest
    Image ID:       docker.io/lachlanevenson/k8s-kubectl@sha256:dd63a5c4a2cb888e88c99aa98a3778bef2156a7ce0e119aa307683f9eee83802
    Port:           3000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 10 Jan 2020 00:35:13 -0500
      Finished:     Fri, 10 Jan 2020 00:35:13 -0500
    Ready:          False
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from k8s-101-role-token-8b25l (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  k8s-101-role-token-8b25l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  k8s-101-role-token-8b25l
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                 From                  Message
  ----     ------     ----                ----                  -------
  Normal   Scheduled  2m6s                default-scheduler     Successfully assigned default/k8s-101-768dfd845b-lrwxx to microk8s-vm
  Normal   Created    77s (x4 over 119s)  kubelet, microk8s-vm  Created container k8s-101
  Normal   Started    77s (x4 over 119s)  kubelet, microk8s-vm  Started container k8s-101
  Warning  BackOff    49s (x7 over 117s)  kubelet, microk8s-vm  Back-off restarting failed container
  Normal   Pulling    34s (x5 over 2m6s)  kubelet, microk8s-vm  Pulling image "lachlanevenson/k8s-kubectl:latest"
  Normal   Pulled     34s (x5 over 119s)  kubelet, microk8s-vm  Successfully pulled image "lachlanevenson/k8s-kubectl:latest"
```

Is there an error in my deployment file that I'm not spotting? Thanks so much in advance for the help. I'll post the logs for the pod as soon as I can get them
